name: Rubocop

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Rubocop Linter
        uses: andrewmcodes/rubocop-linter-action@v2.0.0
        with:
          additional_gems: "rubocop-rails rubocop-performance"
          fail_level: "warning"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
